apiVersion: apps/v1
kind: Deployment
metadata:
  name: cronojobs-front-deployment
spec:
  selector:
    matchLabels:
      app: cronojobs-front
  replicas: 2
  template:
    metadata:
      labels:
        app: cronojobs-front
    spec:
      containers:
        - name: cronojobs-front
          image: cronojobs-front:0.0.1
          ports:
            - containerPort: 80
              name: cronojobsfport