apiVersion: v1
kind: Service
metadata:
  name: cronojobs-front-service
  labels:
    app: cronojobs-front
spec:
  ports:
    - name: cronojobs-front
      port: 80
      nodePort: 30111
  type: NodePort
  selector:
    app: cronojobs-front