apiVersion: v1
kind: Service
metadata:
  name: cronojobs-back-service
  labels:
    app: cronojobs-back
spec:
  ports:
    - name: cronojobs-back
      port: 3000
      nodePort: 30333
  type: NodePort
  selector:
    app: cronojobs-back