apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  labels:
    app: mysql
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: MTIzNDU2  # "123456" en base64
  MYSQL_DATABASE: Y3Jvbm9qb2Jz  # "cronojobs" en base64
  MYSQL_USER: YWRtaW4=          # "admin" en base64
  MYSQL_PASSWORD: YWRtaW4=      # "admin" en base64